import { Box } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Contact from '../components/Home/Contact';
import Hero from '../components/Home/Hero';
import Work from '../components/Home/Work';

const Home: NextPage = () => {
	return (
		<Box width={'full'}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<Work />
			<Contact />
		</Box>
	);
};

export default Home;
